# 

version: '3.9'

services:

  SVC_WEBCLIENT_nextjs:
    build:
      context: .
      dockerfile: dockerfile.pm2
    container_name: SVC_WEBCLIENT_nextjs
    image: howtodocker:nextjs
    environment:
      PORT: 3000
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      # relative path to the Compose file
      - ../svc-storage/var/nextjs:/volume-ro
      - ../svc-storage/var/nextjs:/volume-rw
    networks:
      default:
        ipv4_address: 10.0.0.31 # static ip

  SVC_PROXY_nginx:
    container_name: SVC_PROXY_nginx
    image: howtodocker:nginx
    command: []
    restart: always
    environment: []
    ports:
      # host:container
      - 8000:80
    volumes:
      # relative path to the Compose file
      # read-only volume
      - ../svc-storage/nginx/config:/etc/nginx:ro
      - ../svc-storage/nginx/readonly:/volume-ro:ro
      # read-write volume
      - ../svc-storage/nginx/readwrite:/volume-rw
    networks:
      default:
        ipv4_address: 10.0.0.2 # static ip

networks:

  default: # internal
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24 # mask: 255.255.255.0
          gateway: 10.0.0.1
