version: '3.9'

services:

  nginx:
    build:
      context: "."
      dockerfile: Dockerfile
    container_name: nginx-www-api
    image: howtodocker:nginx_www_api
    command: []
    restart: always
    environment: []
    ports:
      # host:container
      - 8000:80
    volumes:
      # config dir
      - ./volume/nginx/config:/etc/nginx
      # read-only volume
      - ./volume/nginx/readonly:/volume-ro:ro
      # read-write volume
      - ./volume/nginx/readwrite:/volume-rw
    networks:
      default:
        ipv4_address: 10.0.0.2 # static ip

networks:

  default: # internal
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24 # mask: 255.255.255.0
          gateway: 10.0.0.1
