# 

version: '3.9'

services:

  WEBCLIENT:
    build:
      context: ../
      dockerfile: dockerfile.pm2
    container_name: nextjs-with-gcp
    image: howtodocker:nextjs_with_gcp
    environment:
      PORT: 3000
      HOST: 0.0.0.0
      SERVICE_URL: http://c.com:3000
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      # relative path to the Compose file
      - ./volume/nextjs/readonly:/volume-ro
      - ./volume/nextjs/readwrite:/volume-rw
    networks:
      default:
        ipv4_address: 10.0.0.31 # static ip

networks:

  default: # internal
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24 # mask: 255.255.255.0
          gateway: 10.0.0.1
