apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello
  namespace: '69846632868'
  selfLink: /apis/serving.knative.dev/v1/namespaces/69846632868/services/hello
  uid: e7151596-f598-4abe-bbd7-285dde9b8cbb
  resourceVersion: AAXUqypECws
  generation: 1
  creationTimestamp: '2022-01-03T10:40:27.081633Z'
  labels:
    cloud.googleapis.com/location: asia-northeast3
  annotations:
    run.googleapis.com/client-name: cloud-console
    serving.knative.dev/creator: master@joyfun.kr
    serving.knative.dev/lastModifier: master@joyfun.kr
    client.knative.dev/user-image: us-docker.pkg.dev/cloudrun/container/hello
    run.googleapis.com/launch-stage: BETA
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      name: hello-00001-kaz
      annotations:
        run.googleapis.com/client-name: cloud-console
        run.googleapis.com/execution-environment: gen2
        autoscaling.knative.dev/maxScale: '20'
        run.googleapis.com/cpu-throttling: 'false'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: 69846632868-compute@developer.gserviceaccount.com
      containers:
      - image: us-docker.pkg.dev/cloudrun/container/hello
        ports:
        - name: http1
          containerPort: 3000
        resources:
          limits:
            cpu: 4000m
            memory: 4096Mi
  traffic:
  - percent: 100
    latestRevision: true
status:
  observedGeneration: 1
  conditions:
  - type: Ready
    status: 'True'
    lastTransitionTime: '2022-01-03T10:41:37.151755Z'
  - type: ConfigurationsReady
    status: 'True'
    lastTransitionTime: '2022-01-03T10:41:37.045573Z'
  - type: RoutesReady
    status: 'True'
    lastTransitionTime: '2022-01-03T10:41:37.151755Z'
  latestReadyRevisionName: hello-00001-kaz
  latestCreatedRevisionName: hello-00001-kaz
  traffic:
  - revisionName: hello-00001-kaz
    percent: 100
    latestRevision: true
  url: https://hello-6ykrcso3eq-du.a.run.app
  address:
    url: https://hello-6ykrcso3eq-du.a.run.app
