# See https://hub.docker.com/_/nginx

version: "3.9"

services:

  nginx:
    container_name: nginx-custom
    image: nginx:1.21-alpine
    command: []
    restart: always
    environment: []
    ports:
      - 8000:80 # nginxd
    volumes:
      # html dir
      - ./volume/nginx/html:/usr/share/nginx/html:ro
      # config dir
      - ./volume/nginx/config:/etc/nginx
      # log dir
      - ./volume/nginx/log:/var/log/nginx
      # runtime file
      - ./volume/nginx/run:/var/run
      - ./volume/nginx/cache:/var/cache/nginx
    networks:
      default:
        ipv4_address: 10.1.1.2 # static ip
  
networks:

  default:
    ipam:
      driver: default
      config:
        - subnet: 10.1.1.0/24 # mask: 255.255.255.0
          gateway: 10.1.1.1
