# See https://hub.docker.com/_/nginx

version: "3.9"

services:

  nginx:
    container_name: nginx-default
    image: nginx:1.21-alpine
    command: []
    restart: always
    environment: []
    ports:
      - 8000:80 # nginxd
    volumes:
      # html files
      - ./volume/nginx/html:/usr/share/nginx/html:ro
    networks:
      frontend:
        ipv4_address: 10.1.1.2 # static ip
  
networks:

  frontend:
    ipam:
      driver: default
      config:
        - subnet: 10.1.1.0/24 # mask: 255.255.255.0
          gateway: 10.1.1.1
