#
# MongoDB Production Mode
#

# See https://hub.docker.com/_/mongo
FROM mongo:4.4.3-bionic

ENV MONGO_INITDB_ROOT_USERNAME "myadmin"
ENV MONGO_INITDB_ROOT_PASSWORD "myadmin00"

ENTRYPOINT mongod

# TODO
# ENTRYPOINT mongod --config "/etc/mongo/mongod.conf"
