#
# MongoDB Production Mode
#

# See https://hub.docker.com/_/mongo
FROM mongo:4.4.3-bionic

ARG volume_ro=/volume-ro
ARG volume_rw=/volume-rw

RUN echo "ARGs: volume_ro: ${volume_ro}, volume_rw: ${volume_rw}"

