#
# Nginx Development Mode
#
# See https://docs.docker.com/engine/reference/builder/
#

# See https://hub.docker.com/_/nginx
FROM nginx:1.19.2-alpine

#
# directories
#

# read only
ENV NGINX_DIR '/volume-ro/nginx-conf'
ENV PUBLIC_DIR '/volume-ro/public'

# read-write
ENV SRV_DIR '/volume-rw/log/nginx'
RUN mkdir -p ${PUBLIC_DIR} ${SRV_DIR}

# volumes to be bind at runtime
VOLUME [ "/volume-ro", "/volume-rw" ]

#
# run
#
ENTRYPOINT ["nginx", "-c", "/volume-ro/nginx-conf/nginx.conf", "-g", "daemon off;"]
