#
# Nginx Production Mode
#
# See https://docs.docker.com/engine/reference/builder/
#

# See https://hub.docker.com/_/nginx
FROM nginx:1.19.2-alpine

ARG etc_nginx=/etc/nginx
ARG var_nginx=/var/nginx

RUN echo "ARGs: etc_nginx: ${etc_nginx}, var_nginx: ${var_nginx}"

#
# directories
#

# read only
ENV NGINX_DIR "${etc_nginx}"
ENV PUBLIC_DIR "${etc_nginx}/public"

# read-write
ENV LOG_DIR "${var_nginx}/log/nginx"

# volumes to be bound at runtime
VOLUME [ "${etc_nginx}", "${var_nginx}" ]

#
# run
# use *shell form* for variable substitution
ENTRYPOINT nginx -c "$NGINX_DIR/nginx.conf" -g "daemon off;"
