#
# Nginx Development Mode
#
# See https://docs.docker.com/engine/reference/builder/
#

FROM howto:nginx

#
# verbose entrypoint
#
ENV NGINX_ENTRYPOINT_QUIET_LOGS=0

#
# run in debug mode with verbose output
# use *shell form* for variable substitution
ENTRYPOINT nginx -c "$NGINX_DIR/nginx.conf" -g "daemon off;"
