version: '3'
services:
  mongodb:
    image: mongo:4.0.10-xenial
    container_name: mongodb-4.0.10-xenial # [a-zA-Z0-9][a-zA-Z0-9_.-]
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_ROOT_USERNAME=myadmin
      - MONGO_INITDB_ROOT_PASSWORD=myadmin00
      - MONGODB_USERNAME=test
      - MONGODB_PASSWORD=test00
      - MONGODB_DATABASE=test
    volumes:
      - ./etc/mongo:/etc/mongo
      - mongo-data:/data/db
    ports:
      - 27017:27017
    command:
      - --logpath=/dev/null # --config /etc/mongo/mongod.conf # --quiet

volumes:
  mongo-data:
    external:
      name: mongo-data      
# TODO
# networks: 
#   nwas_default:
#     driver: bridge
