# Use root/root000 as user/password credentials
version: '3.9'

services:

  db:
    container_name: mysql-dev
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root000
    volumes:
      # relative path to the Compose file
      - ./mysql-volume/var/mysql/data:/var/lib/mysql

  adminer:
    container_name: mysql-admin
    image: adminer
    restart: always
    ports:
      - 8080:8080
