version: '3.9'

services:

  SVC_PROXY:
    build:
      context: "."
      dockerfile: Dockerfile
    container_name: SVC_PROXY
    image: howtodocker:nginx
    command: []
    restart: always
    environment: []
    ports:
      # host:container
      - 8000:80
    volumes:
      # relative path to the Compose file
      # read-only volume
      - ../svc-storage/nginx/config:/etc/nginx:ro
      - ../svc-storage/nginx/readonly:/volume-ro:ro
      # read-write volume
      - ../svc-storage/nginx/readwrite:/volume-rw
      #- ../svc-storage/nginx/readwrite/cache:/var/cache/nginx
    networks:
      default:
        ipv4_address: 10.0.0.2 # static ip

networks:

  default: # internal
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24 # mask: 255.255.255.0
          gateway: 10.0.0.1
