#
# NodeJS PM2 DEV Mode
#
# See https://docs.docker.com/engine/reference/builder/
#

# override an image from dockerfile.pm2
# NOTE: you need to build the dockerfile.pm2 first
FROM howto:pm2

# volumes to be bound at runtime
VOLUME [ "/workdir" ]

# env mode
ENV NODE_ENV development

# In development mode, we do not copy the source files.
# we will map `/workdir` volume to our working directory in local.
WORKDIR /workdir

# misc
ENV SECRET_KEY "at-docker-file-pm2-dev"

#
# run. use pm2-dev on dev mode
# See https://pm2.keymetrics.io/docs/usage/docker-pm2-nodejs/#development-environment
# use *shell form* for variable substitution
ENTRYPOINT pm2-dev pm2-docker.config.json --env "$NODE_ENV"
